# PBA Nation Contributors
# Grouped by cohort

cohorts:
  pba_2022_cambridge:
    name: "PBA Cambridge 2022"
    start_date: "2022-07-01"
    contributors:
      - github: "ank4n"
        name: "Ankan"

  pba_2024_hongkong:
    name: "PBA Hong Kong 2024"
    start_date: "2024-05-01"
    contributors:
      - github: "asoliman92"
        name: "Boda"
