# PBA Nation Contributors
# Grouped by cohort

cohorts:
  pba_2022_cambridge:
    name: "PBA Cambridge 2022"
    start_date: "2022-07-01"
    contributors:
      - github: "ank4n"
        name: "Ankan"
      - github: "franciscoaguirre"
        name: "franciscoaguirre"

  pba_2024_hongkong:
    name: "PBA Hong Kong 2024"
    start_date: "2024-05-01"
    contributors:
      - github: "TDemeco"
        name: "TDemecoodo"
      - github: "philoniare"
        name: "philoniare"
      - github: "herryho"
        name: "herryho"
      - github: "asoliman92"
        name: "asoliman92"
      - github: "Flaxoos"
        name: "Flaxoos"
      - github: "danebulat"
        name: "danebulat"
      - github: "sgerodes"
        name: "sgerodes"
      - github: "ryanleecode"
        name: "ryanleecode"
      - github: "nomadbitcoin"
        name: "nomadbitcoin"
      - github: "TomaszJarosz"
        name: "TomaszJarosz"
      - github: "aleGiannini"
        name: "aleGiannini"
      - github: "davassi"
        name: "davassi"
      - github: "MBerguer"
        name: "MBerguer"
      - github: "MengLing-P"
        name: "MengLing-P"
      - github: "Mugzar"
        name: "Mugzar"
      - github: "daiagi"
        name: "daiagi"
      - github: "yuxi16"
        name: "yuxi16"
      - github: "cyony95"
        name: "cyony95"
      - github: "noahjoeris"
        name: "noahjoeris"
      - github: "BryanBorck"
        name: "BryanBorck"
      - github: "k-gunjan"
        name: "k-gunjan"
      - github: "Fiono11"
        name: "Fiono11"
      - github: "arjanjohan"
        name: "arjanjohan"
      - github: "usherasnick"
        name: "usherasnick"
      - github: "MrishoLukamba"
        name: "MrishoLukamba"
      - github: "SoftWare2022Testing"
        name: "SoftWare2022Testing"
      - github: "eugenvoronov"
        name: "eugenvoronov"
      - github: "jgutierrezre"
        name: "jgutierrezre"
      - github: "JohnTheWhiteBelt"
        name: "JohnTheWhiteBelt"
      - github: "danicuki"
        name: "danicuki"
      - github: "johandroid"
        name: "johandroid"
      - github: "blockzeek"
        name: "blockzeek"
      - github: "rohibhan"
        name: "rohibhan"
      - github: "vjgaur"
        name: "vjgaur"
      - github: "Anny0nn"
        name: "Anny0nn"
      - github: "marshacb"
        name: "marshacb"
      - github: "MBrozhko34"
        name: "MBrozhko34"
      - github: "AaronLai"
        name: "AaronLai"
      - github: "MarcoDotIO"
        name: "MarcoDotIO"
      - github: "oliverrigonan"
        name: "oliverrigonan"
      - github: "hgminerva"
        name: "hgminerva"
      - github: "felixunforgiven"
        name: "felixunforgiven"
      - github: "Kenun99"
        name: "Kenun99"
      - github: "sepine"
        name: "sepine"
      - github: "wnmMrrd"
        name: "wnmMrrd"
      - github: "marschou1989"
        name: "marschou1989"

  pba_2025_Lucerne:
    name: "PBA Lucerne 2025"
    start_date: "2025-03-23"
    contributors:
      - github: "xd-Abi"
        name: "xd-Abi"
      - github: "rednaxela5950"
        name: "rednaxela5950"
      - github: "allochi"
        name: "allochi"
      - github: "avilliger18"
        name: "avilliger18"
      - github: "AndreyDodonov-EH"
        name: "AndreyDodonov-EH"
      - github: "andrzejSulkowski"
        name: "andrzejSulkowski"
      - github: "soul022"
        name: "soul022"
      - github: "bhargav1000"
        name: "bhargav1000"
      - github: "camaragon"
        name: "camaragon"
      - github: "hippiestank"
        name: "hippiestank"
      - github: "charlesHetterich"
        name: "charlesHetterich"
      - github: "cNikolaou"
        name: "cNikolaou"
      - github: "danielpoellmann"
        name: "danielpoellmann"
      - github: "indieminimalist"
        name: "indieminimalist"
      - github: "dcastrogv"
        name: "dcastrogv"
      - github: "dhirajs0"
        name: "dhirajs0"
      - github: "dimababenko"
        name: "dimababenko"
      - github: "Salgac"
        name: "Salgac"
      - github: "Milosevic02"
        name: "Milosevic02"
      - github: "BukiOffor"
        name: "BukiOffor"
      - github: "emidesejas"
        name: "emidesejas"
      - github: "filippoweb3"
        name: "filippoweb3"
      - github: "cr-eative-dev"
        name: "cr-eative-dev"
      - github: "developerfred"
        name: "developerfred"
      - github: "dutragustavo"
        name: "dutragustavo"
      - github: "castillax"
        name: "castillax"
      - github: "stolbiq"
        name: "stolbiq"
      - github: "Wolfenheimm"
        name: "Wolfenheimm"
      - github: "JesusPerez"
        name: "JesusPerez"
      - github: "jplecha"
        name: "jplecha"
      - github: "jjmiranda"
        name: "jjmiranda"
      - github: "0xjunha"
        name: "0xjunha"
      - github: "refring"
        name: "refring"
      - github: "konrad0960"
        name: "konrad0960"
      - github: "krystian50"
        name: "krystian50"
      - github: "P1sar"
        name: "P1sar"
      - github: "leonardocustodio"
        name: "leonardocustodio"
      - github: "manfioLP"
        name: "manfioLP"
      - github: "lucasdelellis"
        name: "lucasdelellis"
      - github: "luizv"
        name: "luizv"
      - github: "luizhenridev"
        name: "luizhenridev"
      - github: "somthn0somthn"
        name: "somthn0somthn"
      - github: "0xAlvarenga"
        name: "0xAlvarenga"
      - github: "cito-lito"
        name: "cito-lito"
      - github: "mateuszsikora"
        name: "mateuszsikora"
      - github: "matjazonline"
        name: "matjazonline"
      - github: "michaeldev5"
        name: "michaeldev5"
      - github: "michjord0001"
        name: "michjord0001"
      - github: "miquelcabot"
        name: "miquelcabot"
      - github: "ical10"
        name: "ical10"
      - github: "luzanikita"
        name: "luzanikita"
      - github: "Nemanya8"
        name: "Nemanya8"
      - github: "loanMaster"
        name: "loanMaster"
      - github: "realnimish"
        name: "realnimish"
      - github: "niranjanap"
        name: "niranjanap"
      - github: "olegtyshcneko"
        name: "olegtyshcneko"
      - github: "plabarta"
        name: "plabarta"
      - github: "PalomaPe"
        name: "PalomaPe"
      - github: "Ballantines87"
        name: "Ballantines87"
      - github: "prathamesh-mutkure"
        name: "prathamesh-mutkure"
      - github: "reed987"
        name: "reed987"
      - github: "RafalMirowski1"
        name: "RafalMirowski1"
      - github: "amritodosmiltrece "
        name: "amritodosmiltrece "
      - github: "rjammart"
        name: "rjammart"
      - github: "rohitas-git"
        name: "rohitas-git"
      - github: "pallasite99"
        name: "pallasite99"
      - github: "samuel-wakefield"
        name: "samuel-wakefield"
      - github: "skoszuta"
        name: "skoszuta"
      - github: "tiwipaddler"
        name: "tiwipaddler"
      - github: "zalatar242"
        name: "zalatar242"
      - github: "sungwon"
        name: "sungwon"
      - github: "tallesborges"
        name: "tallesborges"
      - github: "Tom-Fitzpatrick"
        name: "Tom-Fitzpatrick"
      - github: "mthomas-io"
        name: "mthomas-io"
      - github: "todortodorovic"
        name: "todortodorovic"
      - github: "wassimans"
        name: "wassimans"
      - github: "yuri-xyz"
        name: "yuri-xyz"
      - github: "Yung-Beef"
        name: "Yung-Beef"

  pba_2025_bali:
    name: "PBA Bali 2025"
    start_date: "2025-23-08"
    contributors:
      - github: "0xdipak"
        name: "0xdipak"
      - github: "0xshae"
        name: "0xshae"
      - github: "agustinustheo"
        name: "agustinustheo"
      - github: "armanthepythonguy"
        name: "armanthepythonguy"
      - github: "bogos"
        name: "bogos"
      - github: "CECILIA-MULANDI"
        name: "CECILIA-MULANDI"
      - github: "cirko33"
        name: "cirko33"
      - github: "danielbui12"
        name: "danielbui12"
      - github: "DeImOs-Sj"
        name: "DeImOs-Sj"
      - github: "DrEverr"
        name: "DrEverr"
      - github: "elle-j"
        name: "elle-j"
      - github: "EmanHerawy"
        name: "EmanHerawy"
      - github: "EnigmaticJ3rry"
        name: "EnigmaticJ3rry"
      - github: "freddyli7"
        name: "freddyli7"
      - github: "iamyxsh"
        name: "iamyxsh"
      - github: "irmannmal"
        name: "irmannmal"
      - github: "jainkrati"
        name: "jainkrati"
      - github: "jbtwist"
        name: "jbtwist"
      - github: "kdonthi"
        name: "kdonthi"
      - github: "khuzama98"
        name: "khuzama98"
      - github: "lawrencefreeman"
        name: "lawrencefreeman"
      - github: "locksley1337"
        name: "locksley1337"
      - github: "LucasGrasso"
        name: "LucasGrasso"
      - github: "Lynette7"
        name: "Lynette7"
      - github: "Magofoco"
        name: "Magofoco"
      - github: "marian-radu"
        name: "marian-radu"
      - github: "melnaquib"
        name: "melnaquib"
      - github: "mudigal"
        name: "mudigal"
      - github: "nikoulai"
        name: "nikoulai"
      - github: "nissan"
        name: "nissan"
      - github: "nullferatu"
        name: "nullferatu"
      - github: "olahfemi"
        name: "olahfemi"
      - github: "raa-dev"
        name: "raa-dev"
      - github: "raymondkfcheung"
        name: "raymondkfcheung"
      - github: "rogerjbos"
        name: "rogerjbos"
      - github: "rose2221"
        name: "rose2221"
      - github: "silicology1"
        name: "silicology1"
      - github: "smohan-dw"
        name: "smohan-dw"
      - github: "ss-deshmukh"
        name: "ss-deshmukh"
      - github: "ssd39"
        name: "ssd39"
      - github: "suenws"
        name: "suenws"
      - github: "talhadaar"
        name: "talhadaar"
      - github: "Tortillaguy"
        name: "Tortillaguy"
      - github: "TypiCal25"
        name: "TypiCal25"
      - github: "ucals"
        name: "ucals"
      - github: "vrom911"
        name: "vrom911"
      - github: "wadkhlemshem"
        name: "wadkhlemshem"
      - github: "wirednkod"
        name: "wirednkod"
      - github: "WonderJL"
        name: "WonderJL"
      - github: "Wsteth"
        name: "Wsteth"
      - github: "yashj09"
        name: "yashj09"
      - github: "yoghantara08"
        name: "yoghantara08"
      - github: "yumingchangsabodota"
        name: "yumingchangsabodota"
