# Repositories to track for Polkadot Bounty Hunters contributions

repositories:
  - owner: "paritytech"
    name: "polkadot-sdk"
    category: "sdk"
  - owner: "paritytech"
    name: "substrate"
    category: "sdk-old"
  - owner: "paritytech"
    name: "cumulus"
    category: "sdk-old"
  - owner: "polkadot-fellows"
    name: "runtimes"
    category: "polkadot"
  - owner: "open-web3-stack"
    name: "open-runtime-module-library"
    category: "parachains"
